<Json> ::= <Object>
         | <Array>

<Object> ::= '{' <Pair>? ( ',' <Pair> )* '}'

<Pair> ::= <STRING> ':' <Value>

<Array> ::= '[' <Value>? ( ',' <Value> )* ']'

<Value> ::= <STRING>
          | '-'? <NUMBER>
          | <Object>
          | <Array>
          | true
          | false
          | null