<Json> ::= <Object>
         | <Array>

<Object> ::= '{' <Pair>? ( ',' <Pair> )* '}'

<Pair> ::= <:String:> ':' <Value>

<Array> ::= '[' <Value>? ( ',' <Value> )* ']'

<Value> ::= <:String:>
          | '-'? <:Number:>
          | <Object>
          | <Array>
          | 'true'
          | 'false'
          | 'null'