<regex> ::= <term>
          | <term> '|' <regex>
<term>  ::= <factor>*
          | <factor>+
<factor>::= <base> <quantifier>?

<base>  ::= <char>
          | '\' <char>
          | '(' <regex> ')'
<quantifier> ::= '*'
               | '+'
               | '?'