<regex> ::= <union>

<union> ::= <concatenation>
          | <union> '|' <concatenation>

<concatenation> ::= <quantification>
                  | <concatenation> <quantification>

<quantification> ::= <elementary>
                    | <elementary> '*'
                    | <elementary> '+'
                    | <elementary> '?'
                    | <elementary> '{' <integer> '}'
                    | <elementary> '{' <integer> ',' '}'
                    | <elementary> '{' ',' <integer> '}'
                    | <elementary> '{' <integer> ',' <integer> '}'

<elementary> ::= <grouping>
                | <character>
                | <dot>
                | <escape>
                | <backreference>
                | <lookaround>

<grouping> ::= '(' <regex> ')'
             | '(?:' <regex> ')'
             | '(?<' <name> '>' <regex> ')'
             | '(?' <modifier> ':' <regex> ')'
             | '(?' <modifier> '<' <name> '>' <regex> ')'

<character> ::= <nondot>
               | <posix>
               | <unicode>
               | <hex>
               | <oct>

# <nondot> ::= any character except '.', '|', '*', '+', '?', '[', ']', '{', '}', '(', ')', '\', '^', '$', '#'

<posix> ::= '\d'
          | '\D'
          | '\s'
          | '\S'
          | '\w'
          | '\W'
          | '\p{...}'
          | '\P{...}'

<unicode> ::= '\p{...}'
             | '\P{...}'

<hex> ::= '\xHH'

<oct> ::= '\0OOO'

<dot> ::= '.'

<escape> ::= '\'
            | '\n'
            | '\r'
            | '\t'
            | '\f'
            | '\b'
            | '\v'
            | '\cX'

<backreference> ::= '\n'

<lookaround> ::= ("?=" <regex> )
                 | ("?!" <regex> )
                 | ("?<=" <regex> )
                 | ("?<!" <regex> )

<modifier> ::= 'i'
             | 'm'
             | 's'
             | 'x'
             | 'a'
             | 'u'
             | 'U'

# <integer> ::= any non-negative integer

# <name> ::= any valid name